net: wireless: bcmdhd: Clean up unused variables
../drivers/net/wireless/bcmdhd/dhd_pno.c:1095:6: error:
variable 'err' set but not used [-Werror,-Wunused-but-set-variable]

../drivers/net/wireless/bcmdhd/dhd_pno.c:3848:7: error:
variable 'status' set but not used [-Werror,-Wunused-but-set-variable]

../drivers/net/wireless/bcmdhd/dhd_pno.c:3848:34: error:
variable 'datalen' set but not used [-Werror,-Wunused-but-set-variable]

../drivers/net/wireless/bcmdhd/dhd_pno.c:3848:27: error:
variable 'flags' set but not used [-Werror,-Wunused-but-set-variable]

../drivers/net/wireless/bcmdhd/dhd_ip.c:1185:26: error:
variable 'old_tcp_hdr_len' set but not used [-Werror,-Wunused-but-set-variable]

../drivers/net/wireless/bcmdhd/wl_cfg80211.c:10647:16: error:
variable 'wiphy' set but not used [-Werror,-Wunused-but-set-variable]

../drivers/net/wireless/bcmdhd/wl_cfg80211.c:10639:19: error:
variable 'ssid' set but not used [-Werror,-Wunused-but-set-variable]

../drivers/net/wireless/bcmdhd/wl_cfgvendor.c:736:36: error:
variable 'dummy' set but not used [-Werror,-Wunused-but-set-variable]

../drivers/net/wireless/bcmdhd/wl_cfgvendor.c:1247:8: error:
variable 'feature_set' set but not used [-Werror,-Wunused-but-set-variable]

../drivers/net/wireless/bcmdhd/dhd_sdio.c:825:8: error:
variable 'val' set but not used [-Werror,-Wunused-but-set-variable]

Change-Id: Iac68e87fd80f8d88354c05f7a59bfee141194e3f